'use client'

// import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google';
import Container from 'react-bootstrap/Container';
import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';
import AppTable from '@/components/app.table';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <Container>
          {children}
        </Container>
        {/* <AppTable /> */}
        <AppFooter />
      </body>
    </html>
  )
}
